version: '3.4'

services:
  backend:
    user: root
    container_name: trips-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - images:/app/wwwroot/images
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys

  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: trips-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=GEAFADsuaifl1ur3453345421
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
  images:
  dataprotection-keys: